# Generated by Django 4.0.4 on 2022-06-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderdetail_order_id_alter_orderdetail_pro_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_completed',
            new_name='is_delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
