# Generated by Django 4.0.4 on 2022-06-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_total_price_orderdetail_pro_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
