# Generated by Django 4.0.4 on 2022-06-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='pro_price',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='total_price',
        ),
    ]
