# Generated by Django 4.0.4 on 2022-06-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_orderdetail_pro_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_delivered',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_received',
        ),
    ]
