# Generated by Django 4.0.4 on 2022-06-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_rename_is_delivered_order_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
