# Generated by Django 4.0.4 on 2022-06-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_is_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='number',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='pro_id',
            new_name='pro_name',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_money',
            field=models.FloatField(default=0),
        ),
    ]
